### PR TITLE
BasicDragger terrain regression fix

### PR DESCRIPTION
**Pull request by mbudk**
Fixed mousecursor not on top of dragObject. This bug seems like a regression introduced in svn version 649. Merged svn versions 459 and 2291 without reintroducing the bug.

### CODE REVIEW

**Comment by mbudk** [comment]
I still had issues with pull request https://github.com/NASAWorldWind/WorldWindJava/pull/6, hence this new request.

**Comment by zglueck** [comment]
Thanks @mbudk for this effort. We actually have a comprehensive BasicDragger overhaul in the pipeline. It will introduce a new interface and shift the implementation away from BasicDragger. It also corrects the behavior of objects drifting from the cursor. The design is still in review, and until it's ready, I'd like to leave this pull request open in case it helps others out while the new BasicDragger is being vetted. Thanks again for sharing your code and hopefully the new BasicDragger (when it is ready) will solve your issues!

**Comment by zglueck** [comment]
@mbudk, thanks again for submitting your work on correcting the behavior of the BasicDragger. The commit f67dee9 on the master branch adds a new Draggable interface which allows you to defined dragging behavior in the class itself. We've also provided utility methods which correct the cursor drifting from the object in the DraggableSupport class that was added in the same commit. Existing World Wind objects now implement the Draggable interface and the appropriate drag utility methods from DraggableSupport, hopefully correcting the dragging issues you observed.

**Comment by mbudk** [comment]
@zglueck, thank you. I've tested on daily 1886 and BasicDragger seems to work fine on terrain now, thanks again. I did need to enable dragging on a PointPlacemark based object of mine to get it working. I also have a SurfacePolyline I'm dragging, on that dragging was enabled by default (in AbstractSurfaceShape). I'm probably missing something, but shouldn't the dragging enabled default policy be the same across renderables (to me, false seems like the best default)?

**Comment by zglueck** [comment]
@mbudk you are correct, I forgot to initialize properly on PointPlacemark, it should indeed be enabled by default. Thanks for catching this, the fix is in commit 6584066.

**Pull request closed without merging**
